### ISSUE TITLE
NameError: uninitialized constant Devise::Strategies::Authenticatable

### ISSUE THREAD

**Issue by calebhaye** [baschtl/devise-token_authenticatable#10]
Just tried running the gem for the first time.  

Not sure why, but I'm getting the following error:

```
rake aborted!
NameError: uninitialized constant Devise::Strategies::Authenticatable
coopgems/ruby-2.1.2@my_project/gems/devise-token_authenticatable-0.3.0/lib/devise/token_authenticatable/strategy.rb:33:in `<module:Strategies>'
coopgems/ruby-2.1.2@my_project/gems/devise-token_authenticatable-0.3.0/lib/devise/token_authenticatable/strategy.rb:4:in `<module:Devise>'
coopgems/ruby-2.1.2@my_project/gems/devise-token_authenticatable-0.3.0/lib/devise/token_authenticatable/strategy.rb:3:in `<top (required)>'
coopgems/ruby-2.1.2@my_project/gems/devise-token_authenticatable-0.3.0/lib/devise/token_authenticatable.rb:1:in `<top (required)>'
coopgems/ruby-2.1.2@my_project/gems/devise-token_authenticatable-0.3.0/lib/devise-token_authenticatable.rb:1:in `<top (required)>'
```

**Comment by calebhaye** [comment]
This is still a problem.  Yes, I have `devise` as a dependency in my gemfile.  Any chance we could work to sort this out.

**Comment by baschtl** [comment]
@calebhaye As you did not answer I thought that you maybe solved it by yourself. Have you tried to run the specs and have a look at the integrated Rails app?

Yes, we can try to sort this out. But it is kind of hard without any further information...
